import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-gradient-to-tr bg-no-repeat 2xl:h-screen w-full from-green-400 to-gray-200">
        {children}
      </body>
    </html>
  );
}
