import "./globals.css";

export const metadata = {
  title: "Score BAC_TN",
  description: "Generated by Bassem Samaali",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className=" bg-gradient-to-tr bg-no-repeat 2xl:h-screen  w-full from-green-400 to-gray-200">
        {children}
      </body>
    </html>
  );
}
